import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createPortal} from '../server/app.mjs';
test('installation and file explorer workflows',async t=>{
 const origin='http://localhost:3100',dataDir=mkdtempSync(join(tmpdir(),'portal-features-')),portal=createPortal({dataDir,origin});const server=portal.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;let cookie='';
 async function req(path,method='GET',body,session=cookie){const res=await fetch(base+'/api'+path,{method,headers:{Origin:origin,'X-Portal-Request':'1',Cookie:session,...(body instanceof FormData?{}:{'Content-Type':'application/json'})},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});return {status:res.status,data:res.headers.get('content-type')?.includes('json')?await res.json():await res.text(),headers:res.headers};}
 try{
 const setup=await req('/auth/setup','POST',{token:readFileSync(portal.tokenPath,'utf8'),name:'test',username:'test',email:'test@example.test',password:'test-password-1234'});cookie=setup.headers.get('set-cookie').split(';')[0];let folder,middle,file,installation,viewerCookie;
 await t.test('installation create, search, update and conflicts',async()=>{let result=await req('/installations','POST',{name:'서버 설치',customer:'테스트 사업장',location:'전산실',installed_on:'2026-09-30',engineer:'테스트',product_version:'v1',status:'installed',notes:'설치 완료'});assert.equal(result.status,201);installation=result.data.installation;assert.equal((await req('/installations?q='+encodeURIComponent('사업장'))).data.total,1);assert.equal((await req('/installations?status=planned')).data.total,0);assert.equal((await req('/installations?from=2026-10-01')).data.total,0);assert.equal((await req('/installations/'+installation.id,'PUT',{...installation,status:'maintenance'})).status,200);assert.equal((await req('/installations/'+installation.id,'PUT',installation)).status,409);});
 await t.test('nested folder navigation and uniqueness',async()=>{folder=(await req('/folders','POST',{name:'매뉴얼'})).data.id;assert.ok(folder);assert.equal((await req('/folders','POST',{name:'매뉴얼'})).status,409);const child=middle=(await req('/folders','POST',{name:'제품 A',parent_id:folder})).data.id;const listing=await req('/library?folder='+child);assert.equal(listing.status,200);assert.deepEqual(listing.data.breadcrumbs.map(f=>f.name),['매뉴얼','제품 A']);assert.equal((await req('/folders/'+folder,'DELETE')).status,409);assert.equal((await req('/folders','POST',{name:'../bad'})).status,400);});
 await t.test('manual upload, scoped search, preview and download',async()=>{const form=new FormData();form.append('file',new Blob(['매뉴얼 본문 <script>alert(1)</script>']),'설치매뉴얼.txt');const uploaded=await req('/manuals?folder='+middle,'POST',form);assert.equal(uploaded.status,201);file=uploaded.data.id;const listing=await req('/library?folder='+middle+'&q='+encodeURIComponent('설치'));assert.equal(listing.status,200);assert.equal(listing.data.files[0].name,'설치매뉴얼.txt');assert.equal((await req('/library')).data.total,0);const preview=await req('/manuals/'+file+'/preview');assert.equal(preview.status,200);assert.match(preview.headers.get('content-type'),/text\/plain/);assert.match(preview.headers.get('content-security-policy'),/sandbox/);assert.match(preview.data,/<script>/);assert.match((await req('/manuals/'+file+'/download')).headers.get('content-disposition'),/attachment/);assert.equal((await req('/manuals/'+file+'/preview','GET',undefined,'')).status,401);});
 await t.test('unsafe formats do not receive inline previews',async()=>{const form=new FormData();form.append('file',new Blob(['<svg onload="alert(1)"></svg>']),'image.svg');const result=await req('/manuals?folder='+middle,'POST',form);assert.equal((await req('/manuals/'+result.data.id+'/preview')).status,415);const fake=new FormData();fake.append('file',new Blob(['<html>bad</html>']),'fake.pdf');const pdf=await req('/manuals?folder='+middle,'POST',fake);assert.equal((await req('/manuals/'+pdf.data.id+'/preview')).status,415);});
 await t.test('viewer can read but cannot mutate installations and library',async()=>{await req('/users','POST',{name:'viewer',username:'viewer',email:'viewer@example.test',password:'test-password-1234',role:'viewer'});const login=await req('/auth/login','POST',{username:'viewer',password:'test-password-1234'});viewerCookie=login.headers.get('set-cookie').split(';')[0];assert.equal((await req('/library','GET',undefined,viewerCookie)).status,200);for(const [path,method,body] of [['/installations','POST',installation],['/folders','POST',{name:'bad'}],['/manuals/'+file,'DELETE',undefined]])assert.equal((await req(path,method,body,viewerCookie)).status,403);});
 await t.test('dashboard uses actual record counts',async()=>{const result=await req('/dashboard');assert.equal(result.data.counts.installations,1);assert.equal(result.data.counts.manuals,3);assert.equal(result.data.installations[0].status,'maintenance');});
 await t.test('uploads above the old 10MB limit are chunked and downloaded intact',async()=>{assert.equal((await req('/manuals/'+file,'DELETE')).status,200);assert.equal((await req('/manuals/'+file+'/download')).status,404);const size=10*1024*1024+1,bytes=new Uint8Array(size);bytes[0]=65;bytes[size-1]=90;const form=new FormData();form.append('file',new Blob([bytes]),'large.txt');const uploaded=await req('/manuals?folder='+middle,'POST',form);assert.equal(uploaded.status,201);const id=uploaded.data.id;assert.equal(portal.db.prepare("SELECT COUNT(*) n FROM file_chunks WHERE scope='manuals' AND file_id=?").get(id).n,11);assert.deepEqual(readdirSync(join(dataDir,'upload-tmp')),[]);const downloaded=await req('/manuals/'+id+'/download');assert.equal(downloaded.status,200);assert.equal(downloaded.data.length,size);assert.equal(downloaded.data[0],'A');assert.equal(downloaded.data.at(-1),'Z');assert.equal((await req('/manuals/'+id,'DELETE')).status,200);assert.equal(portal.db.prepare("SELECT COUNT(*) n FROM file_chunks WHERE scope='manuals' AND file_id=?").get(id).n,0);});
 await t.test('legacy inline attachments remain readable',async()=>{const saved=portal.db.prepare('INSERT INTO manuals(folder_id,name,size,bytes,preview_type,uploaded_by,created_at) VALUES(?,?,?,?,?,?,?)').run(null,'legacy.txt',6,Buffer.from('legacy'),'text/plain; charset=utf-8',1,new Date().toISOString());const id=Number(saved.lastInsertRowid);assert.equal((await req('/manuals/'+id+'/download')).data,'legacy');assert.equal((await req('/manuals/'+id+'/preview')).data,'legacy');assert.equal((await req('/manuals/'+id,'DELETE')).status,200);});
 }finally{await new Promise(r=>server.close(r));portal.db.close();}
});
